export default {
  name: "post",
  title: "Post",
  type: "document",
  fields: [
    {
      title: "Title",
      name: "title",
      type: "string",
    },
    {
      name: "slug",
      title: "Slug",
      type: "slug",
      options: {
        source: "title",
        maxLength: 96,
      },
    },
    {
      title: "MenuItem",
      name: "menuItem",
      type: "reference",
      to: { type: "menuItem" },
      validation: (Rule) => Rule.required(),
    },
    {
      title: "Order",
      name: "order",
      type: "number",
      options: {
        list: [
          { title: 1, value: 1 },
          { title: 2, value: 2 },
          { title: 3, value: 3 },
          { title: 4, value: 4 },
          { title: 5, value: 5 },
          { title: 6, value: 6 },
          { title: 7, value: 7 },
          { title: 8, value: 8 },
          { title: 9, value: 9 },
          { title: 10, value: 10 },
          { title: 11, value: 11 },
          { title: 12, value: 12 },
          { title: 13, value: 13 },
          { title: 14, value: 14 },
          { title: 15, value: 15 },
          { title: 16, value: 16 },
          { title: 17, value: 17 },
          { title: 18, value: 18 },
          { title: 19, value: 19 },
          { title: 20, value: 20 },
          { title: 21, value: 21 },
          { title: 22, value: 22 },
          { title: 23, value: 23 },
          { title: 24, value: 24 },
          { title: 25, value: 25 },
          { title: 26, value: 26 },
          { title: 27, value: 27 },
          { title: 28, value: 28 },
          { title: 29, value: 29 },
          { title: 30, value: 30 },
          { title: 31, value: 31 },
          { title: 32, value: 32 },
          { title: 33, value: 33 },
          { title: 34, value: 34 },
          { title: 35, value: 35 },
          { title: 36, value: 36 },
          { title: 37, value: 37 },
          { title: 38, value: 38 },
          { title: 39, value: 39 },
          { title: 30, value: 30 },
          { title: 31, value: 31 },
          { title: 32, value: 32 },
          { title: 33, value: 33 },
          { title: 34, value: 34 },
          { title: 35, value: 35 },
          { title: 36, value: 36 },
          { title: 37, value: 37 },
          { title: 38, value: 38 },
          { title: 39, value: 39 },
          { title: 40, value: 40 },
        ],
      },
      validation: (Rule) => Rule.required(),
    },
    {
      title: "Main image",
      name: "mainImage",
      type: "image",
      options: {
        hotspot: true,
      },
      validation: (Rule) => Rule.required(),
    },
    {
      title: "Seasons",
      name: "seasons",
      type: "string",
      options: {
        list: [
          { title: "Winter", value: "winter" },
          { title: "Spring", value: "spring" },
          { title: "Summer", value: "summer" },
          { title: "Autumn", value: "autumn" },
        ],
      },
    },
  ],
  orderings: [
    {
      title: "MenuItem",
      name: "orderAsc",
      by: [{ field: "menuItem.order", direction: "asc" }],
    },
    {
      title: "Title",
      name: "titleAsc",
      by: [{ field: "title", direction: "asc" }],
    },
  ],
  preview: {
    select: {
      title: "title",
      subtitle: "menuItem.title",
      media: "mainImage",
    },
  },
}
